Document: zodiac
Title: Debian zodiac Manual
Author: <insert document author here>
Abstract: This manual describes what zodiac is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zodiac/zodiac.sgml.gz

Format: postscript
Files: /usr/share/doc/zodiac/zodiac.ps.gz

Format: text
Files: /usr/share/doc/zodiac/zodiac.text.gz

Format: HTML
Index: /usr/share/doc/zodiac/html/index.html
Files: /usr/share/doc/zodiac/html/*.html

  
